version: '3.8'

services:
  devopslab:
    image: avinash73/demo-app:latest
    ports:
      - "8081:8080"
    networks:
      - app-network

  edhukkudalab:  # New service for another repository
    image: avinash73/another-app:latest  # Replace with your actual image
    ports:
      - "8082:8080"  # Map host port 8082 to container port 8080
    networks:
      - app-network

networks:
  app-network:
